apiVersion: v1
kind: Service
metadata:
 name: orderer-replica-service
 labels:
   app: orderer-replica
spec:
 type: NodePort
 ports:
 - port: 3000
   name: http
   nodePort: 30084
 selector:
   app: orderer-replica