apiVersion: v1
kind: Service
metadata:
 name: orderer-consensus-service3
 labels:
   app: orderer-consensus3
spec:
 type: NodePort
 ports:
 - port: 14005
   name: http
   nodePort: 30281
 selector:
   app: orderer-consensus3