apiVersion: v1
kind: Service
metadata:
 name: orderer-proposer-service
 labels:
   app: orderer-proposer
spec:
 type: NodePort
 ports:
 - port: 14002
   name: http
   nodePort: 30083
 selector:
   app: orderer-proposer