apiVersion: v1
kind: Service
metadata:
 name: orderer-consensus-service2
 labels:
   app: orderer-consensus2
spec:
 type: NodePort
 ports:
 - port: 14004
   name: http
   nodePort: 30181
 selector:
   app: orderer-consensus2