apiVersion: apps/v1
kind: Deployment
metadata:
 name: orderer-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
    app: orderer
 template:
   metadata:
     labels:
       app: orderer
   spec:
     containers:
     - name: orderer
       image: test-app:latest
       ports:
       - containerPort: 3000
