apiVersion: v1
kind: Service
metadata:
 name: server-service-manufacturer
 labels:
   app: server-manufacturer
spec:
 type: NodePort
 externalName: caper-manufacturer
 ports:
 - port: 9001
   name: http
   nodePort: 30085
 selector:
   app: server-manufacturer