apiVersion: v1
kind: Service
metadata:
 name: server-service-manufacturer1
 labels:
   app: server-manufacturer1
spec:
 type: NodePort
 ports:
 - port: 9001
   name: http
   nodePort: 30085
 selector:
   app: server-manufacturer1