apiVersion: v1
kind: Service
metadata:
 name: server-service-buyer3
 labels:
   app: server-buyer3
spec:

 type: NodePort
 ports:
 - port: 13003
   name: http
   nodePort: 30287
 selector:
   app: server-buyer3