apiVersion: v1
kind: Service
metadata:
 name: server-service-carrier3
 labels:
   app: server-carrier3
spec:

 type: NodePort
 ports:
 - port: 12003
   name: http
   nodePort: 30288
 selector:
   app: server-carrier3