apiVersion: v1
kind: Service
metadata:
 name: server-service-supplier2
 labels:
   app: server-supplier2
spec:

 type: NodePort
 ports:
 - port: 11002
   name: http
   nodePort: 30186

 selector:
   app: server-supplier2
