apiVersion: v1
kind: Service
metadata:
 name: server-service-buyer1
 labels:
   app: server-buyer1
spec:

 type: NodePort
 ports:
 - port: 13001
   name: http
   nodePort: 30087
 selector:
   app: server-buyer1