apiVersion: v1
kind: Service
metadata:
 name: server-service-buyer2
 labels:
   app: server-buyer2
spec:

 type: NodePort
 ports:
 - port: 13002
   name: http
   nodePort: 30187
 selector:
   app: server-buyer2